# Generated by Django 4.0.4 on 2022-05-13 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('UniqueID', models.IntegerField(primary_key=True, serialize=False)),
                ('authorId', models.CharField(default='', max_length=70)),
                ('autherResidence', models.CharField(default='', max_length=200)),
                ('communityId', models.CharField(default='', max_length=70)),
                ('content', models.TextField(default='')),
                ('contentId', models.CharField(default='', max_length=70)),
                ('source', models.CharField(default='', max_length=70)),
                ('timestamp', models.DateTimeField()),
                ('title', models.CharField(default='', max_length=70)),
                ('url', models.CharField(default='', max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationConfiguration',
            fields=[
                ('CommunityID', models.IntegerField(primary_key=True, serialize=False)),
                ('highQuality', models.FloatField()),
                ('pattern', models.FloatField()),
                ('popularity', models.FloatField()),
                ('random', models.FloatField()),
                ('timeliness', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('UniqueID', models.IntegerField(primary_key=True, serialize=False)),
                ('communityId', models.CharField(default='', max_length=70)),
                ('eventType', models.BigIntegerField()),
                ('location', models.CharField(default='', max_length=70)),
                ('source', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('userId', models.CharField(default='', max_length=70)),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mindplex.article')),
            ],
            options={
                'db_table': 'Interaction',
            },
        ),
        migrations.AddConstraint(
            model_name='interaction',
            constraint=models.UniqueConstraint(fields=('userId', 'eventType', 'articleId'), name='unique Interaction'),
        ),
    ]
